class SecondGradeEntity {
  final int? id;
  final String name;

  SecondGradeEntity({required this.id, required this.name});

  static String getNameById(int? id) {
    if (id == null) return '';
    return list().firstWhere((e) {
      return e.id == id;
    }, orElse: () => SecondGradeEntity(id: 0, name: '')).name;
  }

  static bool getValidId(int id) {
    return list().any((e) => e.id == id);
  }

  static int? getIndexById(int? id) {
    final index = list().indexWhere((e) => e.id == id);
    return index != -1 ? index : null;
  }

  static int? getIdByName(String? name) {
    final index = list().firstWhere((e) => e.name == name,
        orElse: () => SecondGradeEntity(id: null, name: ''));
    return index.id;
  }

  static List<SecondGradeEntity> list() {
    return [
      SecondGradeEntity(id: null, name: '없음'),
      SecondGradeEntity(id: 218, name: "사찰위원장"),
      SecondGradeEntity(id: 219, name: "사찰위원장/이사"),
      SecondGradeEntity(id: 220, name: "사찰이사"),
      SecondGradeEntity(id: 221, name: "사찰이사/이사"),
      SecondGradeEntity(id: 222, name: "재무이사"),
      SecondGradeEntity(id: 223, name: "전총재"),
      SecondGradeEntity(id: 224, name: "전회장"),
      SecondGradeEntity(id: 225, name: "주 보"),
      SecondGradeEntity(id: 226, name: "명예회원"),
      SecondGradeEntity(id: 227, name: "신입회원"),
      SecondGradeEntity(id: 56, name: "감 사"),
      SecondGradeEntity(id: 57, name: "로타리재단위원장"),
      SecondGradeEntity(id: 58, name: "멤버쉽위원장"),
      SecondGradeEntity(id: 59, name: "이사"),
      SecondGradeEntity(id: 60, name: "10대 회장/이 사"),
      SecondGradeEntity(id: 61, name: "10대회장"),
      SecondGradeEntity(id: 62, name: "10대회장, EDI위원장"),
      SecondGradeEntity(id: 63, name: "11대 회장/이 사"),
      SecondGradeEntity(id: 64, name: "11대,17대 회장/ 클럽관리위원장"),
      SecondGradeEntity(id: 65, name: "11대회장"),
      SecondGradeEntity(id: 66, name: "12대 회장/감 사"),
      SecondGradeEntity(id: 67, name: "12대회장"),
      SecondGradeEntity(id: 68, name: "13대 회장/ 등산회회장"),
      SecondGradeEntity(id: 69, name: "13대 회장/DEI위원장"),
      SecondGradeEntity(id: 70, name: "13대회장,공공이미지"),
      SecondGradeEntity(id: 71, name: "14대 회장/ 봉사프로젝트위원장"),
      SecondGradeEntity(id: 72, name: "14대회장(2006-07)"),
      SecondGradeEntity(id: 73, name: "14대회장, 재무"),
      SecondGradeEntity(id: 74, name: "24대회장(2016-17)"),
      SecondGradeEntity(id: 75, name: "25대 회장/이 사"),
      SecondGradeEntity(id: 76, name: "25대회장(2017-18)"),
      SecondGradeEntity(id: 77, name: "27대회장(2019-20)/로타리재단위원장"),
      SecondGradeEntity(id: 78, name: "28대 회장/이 사"),
      SecondGradeEntity(id: 79, name: "28대회장(2020-21) / 사찰위원장"),
      SecondGradeEntity(id: 81, name: "29대회장(2021-22) / DEI위원장"),
      SecondGradeEntity(id: 82, name: "2대 회장/ 사찰이사"),
      SecondGradeEntity(id: 83, name: "3.4대회장"),
      SecondGradeEntity(id: 84, name: "30대 회장/이 사"),
      SecondGradeEntity(id: 85, name: "31대 회장/클럽관리위원장"),
      SecondGradeEntity(id: 86, name: "32대 회장/재 무"),
      SecondGradeEntity(id: 87, name: "33대 회장/사 찰"),
      SecondGradeEntity(id: 88, name: "3700지구 사무팀장"),
      SecondGradeEntity(id: 89, name: "3대회장"),
      SecondGradeEntity(id: 90, name: "3대회장/사찰위원장"),
      SecondGradeEntity(id: 91, name: "4,5대 회장/이 사"),
      SecondGradeEntity(id: 92, name: "49대회장"),
      SecondGradeEntity(id: 93, name: "4대회장"),
      SecondGradeEntity(id: 94, name: "4대회장/DEI위원장"),
      SecondGradeEntity(id: 95, name: "4대회장/클럽관리위원장"),
      SecondGradeEntity(id: 96, name: "51대회장"),
      SecondGradeEntity(id: 97, name: "54대회장"),
      SecondGradeEntity(id: 98, name: "57대회장"),
      SecondGradeEntity(id: 99, name: "59대회장,DEI위원장"),
      SecondGradeEntity(id: 100, name: "5대회장"),
      SecondGradeEntity(id: 101, name: "62대회장"),
      SecondGradeEntity(id: 102, name: "63대회장,사찰"),
      SecondGradeEntity(id: 103, name: "6대 회장/ 멤버쉽 DEI 위원장"),
      SecondGradeEntity(id: 104, name: "6대회장"),
      SecondGradeEntity(id: 105, name: "6대회장(1998-99)"),
      SecondGradeEntity(id: 106, name: "7대회장"),
      SecondGradeEntity(id: 107, name: "7대회장/이사"),
      SecondGradeEntity(id: 108, name: "8대회장"),
      SecondGradeEntity(id: 109, name: "8대회장(2000-01)"),
      SecondGradeEntity(id: 110, name: "95-96총재"),
      SecondGradeEntity(id: 111, name: "9대,15대 회장/ 로타리재단위원장"),
      SecondGradeEntity(id: 112, name: "9대회장,이사"),
      SecondGradeEntity(id: 113, name: "D.E.I.위원장"),
      SecondGradeEntity(id: 114, name: "DEI 부위원장"),
      SecondGradeEntity(id: 116, name: "DEI위원장"),
      SecondGradeEntity(id: 118, name: "IT 위원장"),
      SecondGradeEntity(id: 119, name: "IT위원장"),
      SecondGradeEntity(id: 120, name: "감사,이사"),
      SecondGradeEntity(id: 121, name: "감사/이사"),
      SecondGradeEntity(id: 122, name: "건강관리위원장"),
      SecondGradeEntity(id: 123, name: "고문"),
      SecondGradeEntity(id: 124, name: "골프위원장"),
      SecondGradeEntity(id: 125, name: "골프회 회장"),
      SecondGradeEntity(id: 126, name: "공공이미지 부위원장"),
      SecondGradeEntity(id: 127, name: "공공이미지(홍보)위원장"),
      SecondGradeEntity(id: 128, name: "공공이미지위워장"),
      SecondGradeEntity(id: 129, name: "공공이미지위원"),
      SecondGradeEntity(id: 142, name: "회장"),
      SecondGradeEntity(id: 147, name: "공공이미지위원장/이사"),
      SecondGradeEntity(id: 148, name: "공공이미지이사"),
      SecondGradeEntity(id: 149, name: "공로명예회원"),
      SecondGradeEntity(id: 150, name: "국제봉사위원장"),
      SecondGradeEntity(id: 151, name: "당연직이사"),
      SecondGradeEntity(id: 152, name: "등산회 회장"),
      SecondGradeEntity(id: 153, name: "로타랙트지도교수"),
      SecondGradeEntity(id: 154, name: "로타리 재단위원장"),
      SecondGradeEntity(id: 155, name: "로타리가족위원장"),
      SecondGradeEntity(id: 156, name: "로타리교육위원장"),
      SecondGradeEntity(id: 157, name: "로타리자원봉사자"),
      SecondGradeEntity(id: 158, name: "로타리재단"),
      SecondGradeEntity(id: 159, name: "로타리재단 부위원장"),
      SecondGradeEntity(id: 160, name: "로타리재단 위원장"),
      SecondGradeEntity(id: 161, name: "로타리재단위원"),
      SecondGradeEntity(id: 162, name: "로타리재단위원장이사"),
      SecondGradeEntity(id: 163, name: "로타리지식위원장"),
      SecondGradeEntity(id: 164, name: "맴버쉽위원"),
      SecondGradeEntity(id: 165, name: "맴버쉽위원장"),
      SecondGradeEntity(id: 166, name: "맴버십위원장"),
      SecondGradeEntity(id: 167, name: "멤버쉽 위원장"),
      SecondGradeEntity(id: 168, name: "멤버쉽(회원) 증강위원장"),
      SecondGradeEntity(id: 169, name: "멤버십"),
      SecondGradeEntity(id: 170, name: "멤버십 부위원장"),
      SecondGradeEntity(id: 172, name: "멤버십이사"),
      SecondGradeEntity(id: 173, name: "멥버쉽위원장"),
      SecondGradeEntity(id: 174, name: "멥버십위원장"),
      SecondGradeEntity(id: 175, name: "명예이사"),
      SecondGradeEntity(id: 177, name: "문화체육위원장"),
      SecondGradeEntity(id: 179, name: "문화체육위원장"),
      SecondGradeEntity(id: 180, name: "무지개 회장/DEI위원장"),
      SecondGradeEntity(id: 181, name: "발전기금위원장"),
      SecondGradeEntity(id: 182, name: "발전위원장"),
      SecondGradeEntity(id: 183, name: "보조금위원장"),
      SecondGradeEntity(id: 184, name: "부 사찰"),
      SecondGradeEntity(id: 185, name: "부 사찰위원장"),
      SecondGradeEntity(id: 186, name: "부 회장"),
      SecondGradeEntity(id: 187, name: "부 감사"),
      SecondGradeEntity(id: 188, name: "부 감사위원장"),
      SecondGradeEntity(id: 189, name: "부 공공이미지위원장"),
      SecondGradeEntity(id: 190, name: "부 봉사프로젝트위원장"),
      SecondGradeEntity(id: 191, name: "부 사무장"),
      SecondGradeEntity(id: 192, name: "부 사찰"),
      SecondGradeEntity(id: 193, name: "부 사찰위원장"),
      SecondGradeEntity(id: 194, name: "부 사찰위원장"),
      SecondGradeEntity(id: 195, name: "부 회장"),
      SecondGradeEntity(id: 196, name: "부회장"),
      SecondGradeEntity(id: 197, name: "부회장 / 이사"),
      SecondGradeEntity(id: 198, name: "부회장(이사)"),
      SecondGradeEntity(id: 199, name: "부회장,이사"),
      SecondGradeEntity(id: 200, name: "봉사프로젝트"),
      SecondGradeEntity(id: 201, name: "봉사프로젝트 부위원장"),
      SecondGradeEntity(id: 202, name: "봉사프로젝트 위원장"),
      SecondGradeEntity(id: 203, name: "봉사프로젝트이사"),
      SecondGradeEntity(id: 204, name: "봉사프로젝트위원"),
      SecondGradeEntity(id: 205, name: "봉사프로젝트위원장"),
      SecondGradeEntity(id: 206, name: "봉사프로젝트위원장, 이사"),
      SecondGradeEntity(id: 207, name: "봉사프로젝트위원장/이사"),
      SecondGradeEntity(id: 208, name: "봉사위원장"),
      SecondGradeEntity(id: 209, name: "사 사"),
      SecondGradeEntity(id: 210, name: "사 사위원장"),
      SecondGradeEntity(id: 211, name: "사찰"),
      SecondGradeEntity(id: 212, name: "사찰 부위원장"),
      SecondGradeEntity(id: 213, name: "사찰 위원장"),
      SecondGradeEntity(id: 214, name: "사찰, 이사"),
      SecondGradeEntity(id: 215, name: "사찰이사"),
      SecondGradeEntity(id: 216, name: "사찰위원"),
      SecondGradeEntity(id: 217, name: "사찰위원장"),
      SecondGradeEntity(id: 229, name: "회원"),
      SecondGradeEntity(id: 231, name: "DEI/IT위원장"),
      SecondGradeEntity(id: 232, name: "감사"),
      SecondGradeEntity(id: 233, name: "공공이미지위원장"),
      SecondGradeEntity(id: 244, name: "멤버십위원장"),
      SecondGradeEntity(id: 245, name: "봉사프로젝트위원장"),
      SecondGradeEntity(id: 246, name: "부회장"),
      SecondGradeEntity(id: 247, name: "이사"),
      SecondGradeEntity(id: 248, name: "재무"),
      SecondGradeEntity(id: 249, name: "직전회장/사찰"),
      SecondGradeEntity(id: 250, name: "차기회장"),
      SecondGradeEntity(id: 251, name: "총무"),
      SecondGradeEntity(id: 252, name: "클럽관리위원장"),
      SecondGradeEntity(id: 258, name: "회장"),
      SecondGradeEntity(id: 259, name: "15대 부회장/ 등산회총무"),
      SecondGradeEntity(id: 260, name: "15대 회장, 사찰"),
      SecondGradeEntity(id: 261, name: "15대 회장/멤버십위원장"),
      SecondGradeEntity(id: 262, name: "15대회장(2007-08)"),
      SecondGradeEntity(id: 263, name: "16대 회장/이 사"),
      SecondGradeEntity(id: 264, name: "16대 회장/재 무"),
      SecondGradeEntity(id: 265, name: "16대(2008-09)/20대회장(2012-13)"),
      SecondGradeEntity(id: 266, name: "17대 부회장/ 재무이사"),
      SecondGradeEntity(id: 267, name: "17대 회장"),
      SecondGradeEntity(id: 268, name: "18대 부회장/ 주보위원장"),
      SecondGradeEntity(id: 269, name: "18대 회장/봉사프로젝트위원장"),
      SecondGradeEntity(id: 270, name: "18대 회장/이 사"),
      SecondGradeEntity(id: 271, name: "19대 회장/ 공공이미지위원장"),
      SecondGradeEntity(id: 272, name: "19대 회장/로타리재단위원장"),
      SecondGradeEntity(id: 273, name: "2022-23년 총재"),
      SecondGradeEntity(id: 274, name: "2024-25년도 2지역대표"),
      SecondGradeEntity(id: 275, name: "20대 회장"),
      SecondGradeEntity(id: 276, name: "20대 회장/감 사"),
      SecondGradeEntity(id: 277, name: "21대 회장/클럽관리위원장"),
      SecondGradeEntity(id: 278, name: "21대회장(2013-14)"),
      SecondGradeEntity(id: 279, name: "22대 회장"),
      SecondGradeEntity(id: 280, name: "22대 회장/사 찰"),
      SecondGradeEntity(id: 281, name: "23대 회장/이 사"),
      SecondGradeEntity(id: 282, name: "23대회장(2015-16)"),
      SecondGradeEntity(id: 286, name: "신회원"),
      SecondGradeEntity(id: 287, name: "원로회원"),
      SecondGradeEntity(id: 288, name: "음향위원장"),
      SecondGradeEntity(id: 289, name: "이 사"),
      SecondGradeEntity(id: 290, name: "이사/전회장"),
      SecondGradeEntity(id: 291, name: "잉사"),
      SecondGradeEntity(id: 292, name: "재 무"),
      SecondGradeEntity(id: 293, name: "재단관리위원장"),
      SecondGradeEntity(id: 294, name: "재무겸차차차기회장"),
      SecondGradeEntity(id: 295, name: "전부회장"),
      SecondGradeEntity(id: 296, name: "전회장/직전총재"),
      SecondGradeEntity(id: 297, name: "초대회장,이사"),
      SecondGradeEntity(id: 298, name: "총무/봉사프로젝트위원장"),
      SecondGradeEntity(id: 299, name: "총무이사"),
      SecondGradeEntity(id: 300, name: "출석/이사"),
      SecondGradeEntity(id: 301, name: "출석이사"),
      SecondGradeEntity(id: 302, name: "클럽관리 부위원장"),
      SecondGradeEntity(id: 303, name: "클럽관리위원장/이사"),
      SecondGradeEntity(id: 304, name: "클럽관리이사"),
      SecondGradeEntity(id: 305, name: "클럽상임 위원장"),
      SecondGradeEntity(id: 307, name: "회 원"),
      SecondGradeEntity(id: 308, name: "회관건립추진특별위원장"),
      SecondGradeEntity(id: 309, name: "회원증강위원장"),
      SecondGradeEntity(id: 312, name: "DEI위원장"),
      SecondGradeEntity(id: 315, name: "로타리재단위원장"),
      SecondGradeEntity(id: 316, name: "보조금위원장"),
      SecondGradeEntity(id: 327, name: "공공이미지위원장"),
      SecondGradeEntity(id: 356, name: "봉사위원장"),
      SecondGradeEntity(id: 394, name: "주보"),
      SecondGradeEntity(id: 395, name: "주보, 잡지위원장"),
      SecondGradeEntity(id: 396, name: "주보위원장"),
      SecondGradeEntity(id: 397, name: "지구기획팀장"),
      SecondGradeEntity(id: 398, name: "지구연수리더"),
      SecondGradeEntity(id: 399, name: "직업분류위원장"),
      SecondGradeEntity(id: 400, name: "직전회장"),
      SecondGradeEntity(id: 401, name: "직전회장 / 사찰위원장"),
      SecondGradeEntity(id: 402, name: "직전회장, 사찰"),
      SecondGradeEntity(id: 403, name: "직전회장/공공이미지위원장"),
      SecondGradeEntity(id: 404, name: "직전회장/사찰위원장"),
      SecondGradeEntity(id: 406, name: "직전회장겸클럽관리위원장"),
      SecondGradeEntity(id: 407, name: "차기회장/이사"),
      SecondGradeEntity(id: 408, name: "차기회장(2025-26)"),
      SecondGradeEntity(id: 409, name: "차기회장*DEI위원장"),
      SecondGradeEntity(id: 410, name: "차차기회장"),
      SecondGradeEntity(id: 411, name: "차차기회장겸봉사프로젝트위원장"),
      SecondGradeEntity(id: 412, name: "차차기회장겸사찰"),
      SecondGradeEntity(id: 413, name: "청소년위원장"),
      SecondGradeEntity(id: 414, name: "초대.2대회장/이사"),
      SecondGradeEntity(id: 415, name: "초대/2대회장"),
      SecondGradeEntity(id: 416, name: "초대회장"),
      SecondGradeEntity(id: 417, name: "총 무"),
      SecondGradeEntity(id: 418, name: "총 무"),
      SecondGradeEntity(id: 419, name: "총무/이사"),
      SecondGradeEntity(id: 420, name: "총재월신기자트레이너"),
      SecondGradeEntity(id: 421, name: "총재특별대표"),
      SecondGradeEntity(id: 422, name: "출석"),
      SecondGradeEntity(id: 423, name: "출석위원"),
      SecondGradeEntity(id: 424, name: "출석위원장"),
      SecondGradeEntity(id: 425, name: "친목위원장"),
      SecondGradeEntity(id: 426, name: "클럽관리"),
      SecondGradeEntity(id: 427, name: "클럽관리부위원장"),
      SecondGradeEntity(id: 428, name: "클럽관리위원"),
      SecondGradeEntity(id: 429, name: "클럽관리위원장/전회장"),
      SecondGradeEntity(id: 430, name: "클럽관리위원장/차기회장"),
      SecondGradeEntity(id: 431, name: "클럽기획위원장"),
      SecondGradeEntity(id: 432, name: "클럽봉사위원장"),
      SecondGradeEntity(id: 433, name: "홍보 팀장"),
      SecondGradeEntity(id: 435, name: "회 원"),
      SecondGradeEntity(id: 436, name: "회 원"),
      SecondGradeEntity(id: 437, name: "회 장"),
      SecondGradeEntity(id: 438, name: "회 장"),
      SecondGradeEntity(id: 439, name: "회관건립추진프로젝트위원장"),
      SecondGradeEntity(id: 441, name: "회원"),
      SecondGradeEntity(id: 442, name: "회장(2024-25)"),
      SecondGradeEntity(id: 443, name: "회장/IT위원장"),
      SecondGradeEntity(id: 452, name: "23대 회장/사 찰"),
      SecondGradeEntity(id: 453, name: "24-25 총재"),
      SecondGradeEntity(id: 454, name: "52대회장"),
      SecondGradeEntity(id: 455, name: "58대회장,로타리재단위원장"),
      SecondGradeEntity(id: 456, name: "5대회장/로타리재단위원장"),
      SecondGradeEntity(id: 457, name: "6대 회 장/이 사"),
      SecondGradeEntity(id: 458, name: "7대 회장/이 사"),
      SecondGradeEntity(id: 459, name: "8대 회 장/이 사"),
      SecondGradeEntity(id: 460, name: "8대회장,이사"),
      SecondGradeEntity(id: 461, name: "9대회장"),
      SecondGradeEntity(id: 462, name: "D.E.I위원장"),
      SecondGradeEntity(id: 463, name: "DEI위원"),
      SecondGradeEntity(id: 464, name: "DEI위원장/이사"),
      SecondGradeEntity(id: 465, name: "SNS위원장"),
      SecondGradeEntity(id: 466, name: "감사/전회장"),
      SecondGradeEntity(id: 467, name: "고문,D.E.I"),
      SecondGradeEntity(id: 468, name: "공공이미지"),
      SecondGradeEntity(id: 469, name: "공공이미지관리위원장"),
      SecondGradeEntity(id: 471, name: "봉사프로젝트위원"),
      SecondGradeEntity(id: 472, name: "부 출석위원장"),
      SecondGradeEntity(id: 473, name: "부사찰위원장"),
      SecondGradeEntity(id: 474, name: "부회장/사찰위원장"),
      SecondGradeEntity(id: 475, name: "사찰"),
      SecondGradeEntity(id: 476, name: "사찰위원장"),
      SecondGradeEntity(id: 477, name: "상조위원장"),
      SecondGradeEntity(id: 478, name: "신세대봉사위원장"),
      SecondGradeEntity(id: 479, name: "신입 회원"),
      SecondGradeEntity(id: 528, name: "의전팀장"),
      SecondGradeEntity(id: 541, name: "IT"),
      SecondGradeEntity(id: 542, name: "DEI"),
      SecondGradeEntity(id: 543, name: "회원증강")
    ];
  }
}
